CREATE DATABASE chat CHARACTER SET utf8 COLLATE utf8_general_ci; 

CREATE TABLE Messages (
    id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `from` VARCHAR(30),
    `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    payload JSON,
    PRIMARY KEY (`id`)
);

ALTER TABLE Messages
 CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
